Revert "Update virtualenv supporting newer entry points (#92)" (#93)
https://github.com/pantsbuild/setup/pull/92 introduced a regression in the `./pants` script. I have reproduced a reported failure to bootstrap a repo by trying to bootstrap the example-python repository on macOS 10.15.7 which results in the following error:

```
~/TC/example-python$ ./pants --version
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   122  100   122    0     0    606      0 --:--:-- --:--:-- --:--:--   610
100   281  100   281    0     0    747      0 --:--:-- --:--:-- --:--:--   747
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 8861k  100 8861k    0     0  7348k      0  0:00:01  0:00:01 --:--:-- 14.2M
Traceback (most recent call last):
  File "/Users/XXX/.cache/pants/setup/bootstrap-Darwin-x86_64/virtualenv-20.2.2/src/virtualenv/__main__.py", line 77, in <module>
    run_with_catch()  # pragma: no cov
  File "/Users/XXX/.cache/pants/setup/bootstrap-Darwin-x86_64/virtualenv-20.2.2/src/virtualenv/__main__.py", line 58, in run_with_catch
    from virtualenv.config.cli.parser import VirtualEnvOptions
ModuleNotFoundError: No module named 'virtualenv'
./pants: line 293: /Users/XXX/.cache/pants/setup/bootstrap-Darwin-x86_64/2.0.0rc1_py38/bin/python: No such file or directory
```

The regression was originally reported on Slack: https://pantsbuild.slack.com/archives/C046T6T9U/p1608991742321800